var items = [
    { unitType: 'kg'  , discr: 'Abacate',      punit: '6.00' },
    { unitType: 'kg', discr: 'Maçã verde',   punit: '10.0' },
    { unitType: 'kg'  , discr: 'Acelga',       punit: '7.00' },
    { unitType: 'kg'  , discr: 'Jiló',         punit: '5.00' },
    { unitType: 'palm', discr: 'Banana',       punit: '3.00' },
    { unitType: 'kg'  , discr: 'Barbante',     punit: '12.0' },
    { unitType: 'kg'  , discr: 'Abobrinha',    punit: '4.00' },
    { unitType: 'unid', discr: 'Alecrim',      punit: '1.00' },
    { unitType: 'unid', discr: 'Alface amer.', punit: '1.50' },
    { unitType: 'unid', discr: 'Alface cres.', punit: '1.50' },
    { unitType: 'unid', discr: 'Alface roxa',  punit: '1.50' },
    { unitType: 'kg'  , discr: 'Alho roxo',    punit: '22.0' },
    { unitType: 'unid', discr: 'Alho-poró',    punit: '2.00' },
    { unitType: 'kg'  , discr: 'Batata doce',  punit: '3.00' },
    { unitType: 'kg'  , discr: 'Batata ing.',  punit: '8.00' },
    { unitType: 'kg'  , discr: 'Berinjela',    punit: '4.00' },
    { unitType: 'kg'  , discr: 'Beterraba',    punit: '5.00' },
    { unitType: 'unid', discr: 'Brócolis',     punit: '8.00' },
    { unitType: 'kg'  , discr: 'Cará',         punit: '7.00' },
    { unitType: 'kg'  , discr: 'Cebola bran.', punit: '6.00' },
    { unitType: 'kg'  , discr: 'Cebola roxa',  punit: '6.00' },
    { unitType: 'unid', discr: 'Cebolinha',    punit: '3.00' },
    { unitType: 'kg'  , discr: 'Cenoura',      punit: '9.00' },
    { unitType: 'unid', discr: 'Chuchu',       punit: '1.00' },
    { unitType: 'maço', discr: 'Coentro',      punit: '1.00' },
    { unitType: 'unid', discr: 'Couve-flor',   punit: '8.00' },
    { unitType: 'unid', discr: 'Couve',        punit: '1.00' },
    { unitType: 'unid', discr: 'Espinafre',    punit: '1.00' },
    { unitType: 'kg'  , discr: 'Feijão verde', punit: '14.0' },
    { unitType: 'kg'  , discr: 'Gengibre',     punit: '20.0' },
    { unitType: 'kg'  , discr: 'Goma',         punit: '5.00' },
    { unitType: 'unid', discr: 'Hortelã',      punit: '1.00' },
    { unitType: 'kg'  , discr: 'Inhame',       punit: '7.00' },
    { unitType: 'kg'  , discr: 'Jerimum',      punit: '5.00' },
    { unitType: 'kg'  , discr: 'Jiló',         punit: '5.00' },
    { unitType: 'unid', discr: 'Laranja com.', punit: '0.70' },
    { unitType: 'kg'  , discr: 'Tomate verm.',         punit: '5.00' },
    { unitType: 'unid', discr: 'Limão',        punit: '0.25' },
    { unitType: 'kg'  , discr: 'Macaxeira',    punit: '5.00' },
    { unitType: 'kg'  , discr: 'Mamão formo.', punit: '3.00' },
    { unitType: 'kg'  , discr: 'Mamão havaí.', punit: '4.50' },
    { unitType: 'kg'  , discr: 'Manga Tommy',  punit: '5.00' },
    { unitType: 'unid', discr: 'Manjericão',   punit: '1.00' },
    { unitType: 'kg'  , discr: 'Maracujá',     punit: '11.0' },
    { unitType: 'kg'  , discr: 'Maxixe',       punit: '5.00' },
    { unitType: 'kg'  , discr: 'Maçã fuji',    punit: '10.0' },
    { unitType: 'kg'  , discr: 'Maçã gala',    punit: '10.0' },
    { unitType: 'kg'  , discr: 'Pimenta che.', punit: '10.0' },
    { unitType: 'kg'  , discr: 'Pepino japo.', punit: '5.00' },
    { unitType: 'kg'  , discr: 'Pepino',       punit: '4.00' },
    { unitType: 'unid', discr: 'Pimentão',     punit: '0.70' },
    { unitType: 'kg'  , discr: 'Quiabo ',      punit: '5.00' },
    { unitType: 'kg'  , discr: 'Repolho roxo', punit: '7.00' },
    { unitType: 'kg'  , discr: 'Repolho ver.', punit: '4.00' },
    { unitType: 'unid', discr: 'Rúcula',       punit: '1.00' },
    { unitType: 'unid', discr: 'Salsa',        punit: '1.00' },
    { unitType: 'kg'  , discr: 'Tempero nat.', punit: '2.00' },
    { unitType: 'kg'  , discr: 'Tomate',       punit: '5.00' },
    { unitType: 'kg'  , discr: 'Uva Vitória',  punit: '14.0' },
    { unitType: 'kg'  , discr: 'Vagem',        punit: '7.00' }
    ];
