var items = [
    { unitType: 'kg'  , discrim: 'Abacate',      punit: '6,00' },
    { unitType: 'unid', discrim: 'Abacaxi',      punit: '5,00' },
    { unitType: 'kg'  , discrim: 'Acelga',       punit: '7,00' },
    { unitType: 'palm', discrim: 'Banana',       punit: '3,00' },
    { unitType: 'kg'  , discrim: 'Abobrinha',    punit: '4,00' },
    { unitType: 'unid', discrim: 'Alecrim',      punit: '1,00' },
    { unitType: 'unid', discrim: 'Alface amer.', punit: '1,50' },
    { unitType: 'unid', discrim: 'Alface cres.', punit: '1,50' },
    { unitType: 'unid', discrim: 'Alface roxa',  punit: '1,50' },
    { unitType: 'kg'  , discrim: 'Alho roxo',    punit: '22,00' },
    { unitType: 'unid', discrim: 'Alho-poró',    punit: '2,00' },
    { unitType: 'kg'  , discrim: 'Batata doce',  punit: '3,00' },
    { unitType: 'kg'  , discrim: 'Batata ing.',    punit: '8,00' },
    { unitType: 'kg'  , discrim: 'Berinjela',    punit: '4,00' },
    { unitType: 'kg'  , discrim: 'Beterraba',    punit: '5,00' },
    { unitType: 'unid', discrim: 'Brócolis',     punit: '8,00' },
    { unitType: 'kg'  , discrim: 'Cará',         punit: '7,00' },
    { unitType: 'kg'  , discrim: 'Cebola bran.', punit: '6,00' },
    { unitType: 'kg'  , discrim: 'Cebola roxa',  punit: '6,00' },
    { unitType: 'unid', discrim: 'Cebolinha',    punit: '3,00' },
    { unitType: 'kg'  , discrim: 'Cenoura',      punit: '9,00' },
    { unitType: 'unid', discrim: 'Chuchu',       punit: '1,00' },
    { unitType: 'maço', discrim: 'Coentro',      punit: '1,00' },
    { unitType: 'unid', discrim: 'Couve-flor',   punit: '8,00' },
    { unitType: 'unid', discrim: 'Couve',        punit: '1,00' },
    { unitType: 'unid', discrim: 'Espinafre',    punit: '1,00' },
    { unitType: 'kg'  , discrim: 'Feijão verde', punit: '14,00' },
    { unitType: 'kg'  , discrim: 'Gengibre',     punit: '20,00' },
    { unitType: 'kg'  , discrim: 'Goma',         punit: '5,00' },
    { unitType: 'unid', discrim: 'Hortelã',      punit: '1,00' },
    { unitType: 'kg'  , discrim: 'Inhame',       punit: '7,00' },
    { unitType: 'kg'  , discrim: 'Jerimum',      punit: '5,00' },
    { unitType: 'kg'  , discrim: 'Jiló',         punit: '5,00' },
    { unitType: 'unid', discrim: 'Laranja com.', punit: '0,70' },
    { unitType: 'unid', discrim: 'Limão',        punit: '0,30' },
    { unitType: 'kg'  , discrim: 'Macaxeira',    punit: '5,00' },
    { unitType: 'kg'  , discrim: 'Mamão formo.', punit: '3,00' },
    { unitType: 'kg'  , discrim: 'Mamão havaí.', punit: '4,50' },
    { unitType: 'kg'  , discrim: 'Manga Tommy',  punit: '5,00' },
    { unitType: 'unid', discrim: 'Manjericão',   punit: '1,00' },
    { unitType: 'kg'  , discrim: 'Maracujá',     punit: '11,00' },
    { unitType: 'kg'  , discrim: 'Maxixe',       punit: '5,00' },
    { unitType: 'kg'  , discrim: 'Maçã fuji',    punit: '10,00' },
    { unitType: 'kg'  , discrim: 'Maçã gala',    punit: '10,00' },
    { unitType: 'kg'  , discrim: 'Pimenta che.', punit: '10,00' },
    { unitType: 'kg'  , discrim: 'Pepino japo.', punit: '5,00' },
    { unitType: 'kg'  , discrim: 'Pepino',       punit: '4,00' },
    { unitType: 'unid', discrim: 'Pimentão',     punit: '0,70' },
    { unitType: 'kg'  , discrim: 'Quiabo ',      punit: '5,00' },
    { unitType: 'kg'  , discrim: 'Repolho roxo', punit: '7,00' },
    { unitType: 'kg'  , discrim: 'Repolho ver.', punit: '4,00' },
    { unitType: 'unid', discrim: 'Rúcula',       punit: '1,00' },
    { unitType: 'unid', discrim: 'Salsa',        punit: '1,00' },
    { unitType: 'kg'  , discrim: 'Tempero nat.', punit: '2,00' },
    { unitType: 'kg'  , discrim: 'Tomate',       punit: '5,00' },
    { unitType: 'kg'  , discrim: 'Uva Vitória',  punit: '14,00' },
    { unitType: 'kg'  , discrim: 'Vagem',        punit: '7,00' }
    ];
